"""
EditorAgent: Validates generated marketing content against factsheets.

Responsibilities:
- Validate factsheet accuracy
- Check for hallucinated features
- Verify information correctness
- Assess tone and quality
- Return structured approval/rejection with feedback
"""

import json
import os
from typing import Optional, Dict, Any, List
from datetime import datetime
from openai import OpenAI


class EditorAgent:
    """
    An AI agent that validates and reviews marketing content.
    Checks for factual accuracy, hallucinations, and quality metrics.
    """

    def __init__(self, api_key: Optional[str] = None, model: str = "gpt-4o-mini"):
        """
        Initialize the EditorAgent with OpenAI client.

        Args:
            api_key: OpenAI API key. If not provided, uses OPENAI_API_KEY env var.
            model: The OpenAI model to use (default: gpt-4o-mini)
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "OpenAI API key not provided. Set OPENAI_API_KEY environment variable or pass api_key parameter."
            )

        self.client = OpenAI(api_key=self.api_key)
        self.model = model

    def validate_content(
        self, factsheet: Dict[str, Any], generated_content: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Validate generated content against factsheet.

        Args:
            factsheet: Original product factsheet
            generated_content: Content generated by CopywriterAgent (contains blog_post, tweet_thread, email_teaser)

        Returns:
            Validation result with:
            - overall_status: APPROVED or REJECTED
            - blog_post_review: Review of blog post
            - tweet_thread_review: Review of tweet thread
            - email_teaser_review: Review of email teaser
            - hallucinations: List of hallucinated or inaccurate claims
            - tone_quality: Quality assessment of tone
            - recommendations: Improvement suggestions
            - confidence_score: Confidence in validation (0-100)
        """
        self._validate_inputs(factsheet, generated_content)

        try:
            blog_review = self._validate_blog_post(
                factsheet, generated_content.get("blog_post", "")
            )
            tweet_review = self._validate_tweet_thread(
                factsheet, generated_content.get("tweet_thread", [])
            )
            email_review = self._validate_email_teaser(
                factsheet, generated_content.get("email_teaser", "")
            )
            hallucinations = self._detect_hallucinations(
                factsheet, generated_content
            )
            tone_quality = self._assess_tone_quality(factsheet, generated_content)

            # Determine overall status
            overall_status = self._determine_status(
                blog_review, tweet_review, email_review, hallucinations
            )

            result = {
                "status": "success",
                "timestamp": datetime.utcnow().isoformat(),
                "product_name": factsheet.get("product_name"),
                "validation": {
                    "overall_status": overall_status,
                    "blog_post_review": blog_review,
                    "tweet_thread_review": tweet_review,
                    "email_teaser_review": email_review,
                    "hallucinations_detected": hallucinations,
                    "tone_quality": tone_quality,
                    "confidence_score": self._calculate_confidence(
                        blog_review, tweet_review, email_review, hallucinations
                    ),
                },
                "recommendations": self._generate_recommendations(
                    blog_review, tweet_review, email_review, hallucinations
                ),
            }

            return result

        except Exception as e:
            raise Exception(f"Error during content validation: {e}")

    def _validate_inputs(
        self, factsheet: Dict[str, Any], generated_content: Dict[str, Any]
    ) -> None:
        """Validate that inputs are in correct format."""
        if not factsheet:
            raise ValueError("Factsheet cannot be empty")

        if not generated_content:
            raise ValueError("Generated content cannot be empty")

        required_factsheet_fields = [
            "product_name",
            "key_features",
            "value_proposition",
        ]
        missing = [f for f in required_factsheet_fields if f not in factsheet]
        if missing:
            raise ValueError(f"Factsheet missing: {', '.join(missing)}")

    def _validate_blog_post(
        self, factsheet: Dict[str, Any], blog_post: str
    ) -> Dict[str, Any]:
        """
        Validate blog post content.

        Args:
            factsheet: Original product factsheet
            blog_post: Generated blog post text

        Returns:
            Review dictionary with findings
        """
        prompt = self._build_blog_validation_prompt(factsheet, blog_post)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert content editor and fact-checker. Validate marketing content for accuracy, tone, and quality. Return a JSON response.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            response_format={"type": "json_object"},
        )

        review = json.loads(response.choices[0].message.content)
        return review

    def _build_blog_validation_prompt(
        self, factsheet: Dict[str, Any], blog_post: str
    ) -> str:
        """Build the blog post validation prompt."""
        features_str = "\n".join(
            [f"- {f}" for f in factsheet.get("key_features", [])]
        )
        specs_str = json.dumps(factsheet.get("technical_specs", {}), indent=2)

        return f"""
You are a professional editor validating a blog post against original product information.

ORIGINAL PRODUCT INFORMATION:
Product Name: {factsheet.get('product_name')}
Value Proposition: {factsheet.get('value_proposition')}
Target Audience: {factsheet.get('target_audience')}

Key Features:
{features_str}

Technical Specs:
{specs_str}

BLOG POST TO VALIDATE:
{blog_post}

Analyze the blog post and return a JSON object with:
{{
  "is_accurate": boolean - is the content factually accurate based on product info?,
  "tone_assessment": string - describe the tone (professional/appropriate/engaging),
  "accuracy_score": number 0-100 - how accurate is the content?,
  "tone_score": number 0-100 - quality of tone and engagement,
  "inaccuracies": [list of strings] - specific inaccurate claims found,
  "missing_info": [list of strings] - important product info not mentioned,
  "excessive_claims": [list of strings] - over-promised or hyperbolic statements,
  "strengths": [list of strings] - what works well in the blog post,
  "improvement_areas": [list of strings] - areas for improvement,
  "overall_quality": string - EXCELLENT/GOOD/ADEQUATE/POOR
}}

Return ONLY valid JSON. Be critical but fair.
"""

    def _validate_tweet_thread(
        self, factsheet: Dict[str, Any], tweets: List[str]
    ) -> Dict[str, Any]:
        """
        Validate tweet thread content.

        Args:
            factsheet: Original product factsheet
            tweets: List of 5 tweets

        Returns:
            Review dictionary with findings
        """
        prompt = self._build_tweet_validation_prompt(factsheet, tweets)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert social media strategist and fact-checker. Validate tweet threads for accuracy, engagement, and compliance. Return a JSON response.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            response_format={"type": "json_object"},
        )

        review = json.loads(response.choices[0].message.content)
        return review

    def _build_tweet_validation_prompt(
        self, factsheet: Dict[str, Any], tweets: List[str]
    ) -> str:
        """Build the tweet thread validation prompt."""
        features_str = ", ".join(factsheet.get("key_features", [])[:5])
        tweets_str = "\n".join([f"{i+1}/ {t}" for i, t in enumerate(tweets)])

        return f"""
You are a social media expert validating a tweet thread against original product information.

ORIGINAL PRODUCT INFORMATION:
Product: {factsheet.get('product_name')}
Value Proposition: {factsheet.get('value_proposition')}
Target Audience: {factsheet.get('target_audience')}
Key Features: {features_str}

TWEET THREAD TO VALIDATE:
{tweets_str}

Analyze the tweet thread and return a JSON object with:
{{
  "is_accurate": boolean - are the tweets factually accurate?,
  "engagement_quality": string - describe engagement quality,
  "accuracy_score": number 0-100 - factual accuracy,
  "engagement_score": number 0-100 - likelihood to engage audience,
  "character_compliance": [list] - check each tweet is under 280 chars,
  "inaccuracies": [list of strings] - factually incorrect claims,
  "hallucinations": [list of strings] - claims not supported by product info,
  "missing_value_prop": boolean - is value proposition clearly communicated?,
  "tone_consistency": string - is tone consistent across tweets?,
  "tweet_quality": [list] - quality assessment for each of 5 tweets,
  "improvement_areas": [list of strings] - suggestions for improvement,
  "overall_quality": string - EXCELLENT/GOOD/ADEQUATE/POOR
}}

Be thorough in fact-checking. Flag any claims not directly supported by product info.
"""

    def _validate_email_teaser(
        self, factsheet: Dict[str, Any], email_teaser: str
    ) -> Dict[str, Any]:
        """
        Validate email teaser content.

        Args:
            factsheet: Original product factsheet
            email_teaser: Generated email teaser text

        Returns:
            Review dictionary with findings
        """
        prompt = self._build_email_validation_prompt(factsheet, email_teaser)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert email copywriter and compliance officer. Validate email copy for accuracy, effectiveness, and compliance. Return a JSON response.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            response_format={"type": "json_object"},
        )

        review = json.loads(response.choices[0].message.content)
        return review

    def _build_email_validation_prompt(
        self, factsheet: Dict[str, Any], email_teaser: str
    ) -> str:
        """Build the email teaser validation prompt."""
        features_str = "\n".join(
            [f"- {f}" for f in factsheet.get("key_features", [])[:5]]
        )

        return f"""
You are an email marketing expert validating email copy against original product information.

ORIGINAL PRODUCT INFORMATION:
Product: {factsheet.get('product_name')}
Value Proposition: {factsheet.get('value_proposition')}
Target Audience: {factsheet.get('target_audience')}

Key Features:
{features_str}

EMAIL TEASER TO VALIDATE:
{email_teaser}

Analyze the email teaser and return a JSON object with:
{{
  "is_accurate": boolean - is the content factually accurate?,
  "persuasiveness": number 0-100 - likelihood to drive opens/clicks,
  "accuracy_score": number 0-100 - factual accuracy,
  "compliance_score": number 0-100 - marketing compliance (no false claims),
  "inaccuracies": [list of strings] - factually incorrect claims,
  "hallucinations": [list of strings] - unsupported claims,
  "value_prop_clarity": number 0-100 - how clear is the value proposition?,
  "call_to_action": string - assess the implied CTA strength,
  "tone_appropriateness": string - is tone appropriate for email?,
  "improvement_areas": [list of strings] - suggestions for improvement,
  "overall_quality": string - EXCELLENT/GOOD/ADEQUATE/POOR
}}

Focus on: factual accuracy, compliance, and whether claims can be supported.
"""

    def _detect_hallucinations(
        self, factsheet: Dict[str, Any], generated_content: Dict[str, Any]
    ) -> List[str]:
        """
        Detect hallucinated or unsupported claims in generated content.

        Args:
            factsheet: Original product factsheet
            generated_content: Generated marketing content

        Returns:
            List of hallucinated claims found
        """
        prompt = self._build_hallucination_detection_prompt(
            factsheet, generated_content
        )

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are a fact-checker specialized in detecting hallucinations and unsupported claims in marketing content. Return a JSON response.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            response_format={"type": "json_object"},
        )

        result = json.loads(response.choices[0].message.content)
        return result.get("hallucinations", [])

    def _build_hallucination_detection_prompt(
        self, factsheet: Dict[str, Any], generated_content: Dict[str, Any]
    ) -> str:
        """Build the hallucination detection prompt."""
        content_text = " ".join(
            [
                generated_content.get("blog_post", ""),
                " ".join(generated_content.get("tweet_thread", [])),
                generated_content.get("email_teaser", ""),
            ]
        )

        features_str = ", ".join(factsheet.get("key_features", []))
        specs_str = json.dumps(factsheet.get("technical_specs", {}))

        return f"""
Analyze the generated marketing content for hallucinations - claims that are NOT supported by the original product information.

ORIGINAL PRODUCT INFORMATION:
Product: {factsheet.get('product_name')}
Features: {features_str}
Specs: {specs_str}
Target Audience: {factsheet.get('target_audience')}

GENERATED CONTENT:
{content_text[:2000]}

Identify any claims in the generated content that:
1. Are not mentioned in the product information
2. Contradict the product information
3. Are exaggerated beyond what's claimed
4. Make specific claims without supporting data
5. Are vague marketing hype without substance

Return a JSON object with:
{{
  "hallucinations": [list of specific hallucinated claims found],
  "hallucination_count": number,
  "severity": string - CRITICAL/HIGH/MEDIUM/LOW,
  "unsupported_claims": [list of claims needing verification]
}}

Be specific about which claims are hallucinated.
"""

    def _assess_tone_quality(
        self, factsheet: Dict[str, Any], generated_content: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Assess overall tone and quality of generated content.

        Args:
            factsheet: Original product factsheet
            generated_content: Generated marketing content

        Returns:
            Tone quality assessment
        """
        prompt = self._build_tone_assessment_prompt(factsheet, generated_content)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert in brand voice, copywriting, and content quality. Assess tone and quality comprehensively. Return a JSON response.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            response_format={"type": "json_object"},
        )

        assessment = json.loads(response.choices[0].message.content)
        return assessment

    def _build_tone_assessment_prompt(
        self, factsheet: Dict[str, Any], generated_content: Dict[str, Any]
    ) -> str:
        """Build the tone assessment prompt."""
        return f"""
Assess the overall tone and quality of this marketing content suite.

PRODUCT CONTEXT:
Product: {factsheet.get('product_name')}
Value Proposition: {factsheet.get('value_proposition')}
Target Audience: {factsheet.get('target_audience')}

CONTENT TO ASSESS:
Blog Post: {generated_content.get('blog_post', '')[:500]}...
Tweet Thread: {generated_content.get('tweet_thread', [])}
Email Teaser: {generated_content.get('email_teaser', '')}

Return a JSON object with:
{{
  "tone_consistency": number 0-100 - consistency across all formats,
  "brand_alignment": number 0-100 - alignment with product positioning,
  "audience_fit": number 0-100 - appropriateness for target audience,
  "professionalism": number 0-100 - professional quality level,
  "persuasiveness": number 0-100 - persuasive power and impact,
  "originality": number 0-100 - originality and uniqueness,
  "clarity": number 0-100 - clarity of messaging,
  "tone_description": string - describe the overall tone,
  "strengths": [list of 3-5 strengths],
  "weaknesses": [list of 3-5 weaknesses],
  "overall_score": number 0-100 - overall quality score
}}
"""

    def _determine_status(
        self,
        blog_review: Dict,
        tweet_review: Dict,
        email_review: Dict,
        hallucinations: List[str],
    ) -> str:
        """
        Determine overall approval status.

        Args:
            blog_review: Blog post review
            tweet_review: Tweet thread review
            email_review: Email teaser review
            hallucinations: List of hallucinations

        Returns:
            APPROVED or REJECTED
        """
        # Reject if critical hallucinations detected
        if hallucinations and len(hallucinations) > 3:
            return "REJECTED"

        # Reject if major inaccuracies detected
        blog_accuracy = blog_review.get("accuracy_score", 100)
        tweet_accuracy = tweet_review.get("accuracy_score", 100)
        email_accuracy = email_review.get("accuracy_score", 100)

        avg_accuracy = (blog_accuracy + tweet_accuracy + email_accuracy) / 3

        if avg_accuracy < 70:
            return "REJECTED"

        # Reject if tone quality is poor
        blog_quality = blog_review.get("overall_quality", "")
        tweet_quality = tweet_review.get("overall_quality", "")
        email_quality = email_review.get("overall_quality", "")

        poor_count = sum(
            1 for q in [blog_quality, tweet_quality, email_quality] if q == "POOR"
        )
        if poor_count > 1:
            return "REJECTED"

        return "APPROVED"

    def _calculate_confidence(
        self,
        blog_review: Dict,
        tweet_review: Dict,
        email_review: Dict,
        hallucinations: List[str],
    ) -> int:
        """Calculate confidence score for the validation."""
        # Base confidence
        confidence = 85

        # Reduce for hallucinations
        confidence -= len(hallucinations) * 5

        # Reduce for inaccuracies
        accuracy_scores = [
            blog_review.get("accuracy_score", 100),
            tweet_review.get("accuracy_score", 100),
            email_review.get("accuracy_score", 100),
        ]

        avg_accuracy = sum(accuracy_scores) / len(accuracy_scores)
        confidence = int((confidence * avg_accuracy) / 100)

        return max(0, min(100, confidence))

    def _generate_recommendations(
        self,
        blog_review: Dict,
        tweet_review: Dict,
        email_review: Dict,
        hallucinations: List[str],
    ) -> List[str]:
        """Generate recommendations for improvement."""
        recommendations = []

        # Blog recommendations
        if blog_review.get("improvement_areas"):
            recommendations.extend(
                [f"Blog: {item}" for item in blog_review.get("improvement_areas", [])]
            )

        # Tweet recommendations
        if tweet_review.get("improvement_areas"):
            recommendations.extend(
                [
                    f"Tweets: {item}"
                    for item in tweet_review.get("improvement_areas", [])
                ]
            )

        # Email recommendations
        if email_review.get("improvement_areas"):
            recommendations.extend(
                [
                    f"Email: {item}"
                    for item in email_review.get("improvement_areas", [])
                ]
            )

        # Hallucination recommendations
        if hallucinations:
            recommendations.append(
                f"Remove or verify {len(hallucinations)} hallucinated claims"
            )

        return recommendations[:10]  # Limit to top 10 recommendations

    def batch_validate(
        self,
        validations: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Validate multiple content items.

        Args:
            validations: List of dicts with 'factsheet' and 'generated_content'

        Returns:
            List of validation results
        """
        results = []
        for i, item in enumerate(validations):
            try:
                result = self.validate_content(
                    item.get("factsheet", {}), item.get("generated_content", {})
                )
                results.append(result)
            except Exception as e:
                results.append(
                    {
                        "status": "error",
                        "timestamp": datetime.utcnow().isoformat(),
                        "error": str(e),
                        "index": i,
                    }
                )
        return results

    def to_json(self, result: Dict[str, Any]) -> str:
        """Convert result to formatted JSON string."""
        return json.dumps(result, indent=2)


def main():
    """Example usage of EditorAgent."""
    sample_factsheet = {
        "product_name": "CloudVault Pro",
        "key_features": [
            "Unlimited cloud storage",
            "Military-grade encryption",
            "Real-time team collaboration",
            "AI-powered file organization",
        ],
        "technical_specs": {
            "storage": "Unlimited",
            "encryption": "AES-256",
            "team_members": "Up to 1000",
            "integrations": "50+",
            "uptime_sla": "99.99%",
        },
        "target_audience": "Enterprise teams seeking secure cloud storage",
        "value_proposition": "Secure, scalable cloud storage enabling seamless team collaboration",
    }

    sample_content = {
        "blog_post": "CloudVault Pro represents the future of enterprise cloud storage...",
        "tweet_thread": [
            "1/ Enterprise cloud storage is broken. Teams waste hours managing file chaos.",
            "2/ CloudVault Pro changes everything with unlimited secure storage and real-time collaboration.",
            "3/ Built for teams of any size, with military-grade encryption protecting your data 24/7.",
            "4/ Perfect for enterprises that need scalability without compromise on security.",
            "5/ Ready to transform how your team works? Discover CloudVault Pro today.",
        ],
        "email_teaser": "Discover how CloudVault Pro simplifies enterprise collaboration while keeping your data secure.",
    }

    try:
        agent = EditorAgent()
        result = agent.validate_content(sample_factsheet, sample_content)
        print(agent.to_json(result))
    except Exception as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()
